---
title: "ESM 262: Computing for Environmental Science and Management (Assignment 3)"
author: "Nathaniel Burola"
date: "3/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Attaching packages 
```{r}
library(rainbow)
library(tidyverse)
library(here)
library(devtools)
library(roxygen2)
library(Rd2roxygen)
library(rio)
library(testthat)
```

## Reading in the data with the here package 
```{r}
sbdata <- read_csv(here("data", "sbraindata.rda"))
```

## Removing NA values from the data 
```{r}
x$V7 <- NULL

#Removing all of the NA values from the X7 column making it completely gone 
```

## Experimentation with the data to make sure the dang package works! 
```{r}
#Need to load sbraindata.rda into the workspace in order for the functions to work 
#File will read as x which is then written into the functions 

trial_1 <- flooding(probability, land_size = 41.99, maximum = 2.02)
#trial_1 is 0.848198

trial_2 <- maximum(rainvalue)
#trial_2 is 2.02

trial_3 <- minimum(rainnum)
#trial 3 is 0.01

```







